spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev

mybatis:
  #指定mybatis全局配置文件的位置
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

comment.avatar: /images/avatar.png

aliyun:
  oss:
    file:
      endpoint: zjh
      keyid: zjh
      keysecret: zjh
      filehost: zjh
      bucketname: zjh