spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.213.114:3306/ezhan?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: MyNewPass4!

logging:
  level:
    root: info
    com.hogwarts.springboot: debug
  file: log/blog-dev.log

